# This file is made by Marcelo Gauy

# it takes the mouse movement in a grid generated by one mouse path script and translates that into the sequence of place cells that get excitatory input



function placecellsequence(mousepathpositions, N_placecells, mousesize, gridsize_x, gridsize_y)
	pathlength = size(mousepathpositions,1)
	cellpathsequence = zeros(Int64, mousesize*mousesize,pathlength)
	for index = 1:pathlength
		pos_x = mousepathpositions[index,1]
		pos_y = mousepathpositions[index,2]
		for x_size = 0:mousesize-1
			for y_size = 1:mousesize
				first_index = mousesize*x_size + y_size
				cellpathsequence[first_index, index] = convert(Int64,gridsize_y*(pos_x+x_size-1) + pos_y+y_size-1)
			end
		end
	end
	return cellpathsequence
end
